services:
  #
  milvus:
    image: milvusdb/milvus:v2.3.1
    container_name: milvus
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1.0"
        reservations:
          memory: 1g
    ports:
      - "19530:19530"
      - "9091:9091"

  mysql:
    image: mysql:8.0
    restart: always
    command:
      - --default_authentication_plugin=mysql_native_password
      - --binlog-format=ROW
      - --server-id=1
    environment:
      MYSQL_ROOT_PASSWORD: muxiStudioLLM
      TZ: Asia/Shanghai
    volumes:
      - ./volume/conf:/etc/mysql/conf.d
      - ./volume/data:/var/lib/mysql
      - ./volume/logs:/var/log/mysql
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13306:3306"













